datasets:
  hoch2022multiplexed:
    name: hoch2022multiplexed
    path: /mnt/aimm/scratch/datasets_v2/hoch2022multiplexed
    modality: imc
    standardization: identity
    resolution: 1.0
    filter_list: []
    use_mean_std: False
    disable_quantile_mask: True
    replace_nuclear_uniprot_ids: True