datasets:
  rigamonti2024integrating:
    name: rigamonti2024integrating
    path: /path/to/datasets/rigamonti2024integrating
    modality: imc
    standardization: identity
    resolution: 1.0
    filter_list: []
    use_mean_std: False
    disable_quantile_mask: True