datasets:
  schurch2020coordinated:
    name: schurch2020coordinated
    path: /path/to/datasets/schurch2020coordinated
    modality: codex
    standardization: identity
    resolution: 0.37744
    use_mean_std: False
    disable_quantile_mask: True
    replace_nuclear_uniprot_ids: True
