

model:
  _target_: models.virtues.virtues_model.SporaVirTuesWrapper
  model_name: virtues
  checkpoint_path: /path/to/model_weights/virtues/model.safetensors
  marker_embeddings_dir: /path/to/marker_embeddings/esm2_t30_150M_UR50D
  patch_size: 8
  model_dim: 512
  feedforward_dim: 1024
  encoder_pattern: hvhvhvhvhvhvhvhv
  num_encoder_heads: 8
  decoder_pattern: ffff
  num_decoder_heads: 8
  num_decoder_hidden_layers: 0
  positional_embedding_type: rope
  dropout: 0.0
  group_layers: False
  norm_after_encoder_decoder: True
  tile_size: 128