datasets:
  cords2023cancer:
    benchmarks:
      cell_annotation: 
        cell_type_atlas:
          label_col: cell_type_atlas
          excluded_classes: [Unknown,]
          cell_types:
            Tumor:
              - Keratin-AE1-AE3
            Fibroblasts /Stroma:
              - FAP
              - SMA
              - Vimentin
              - Fibronectin-Collagen-I
              - Cadherin-11
            Myeloid:
              - CD68
              - CD11c
              - HLA-DR
            CD4 T cell:
              - CD3
              - CD4
            CD8 T cell:
              - CD3
              - CD8a
            B cell:
              - CD20
            Vessel / Endo.:
              - CD31
              - Podoplanin
          eval_cell_types: ['Tumor', 'Fibroblasts /Stroma', 'Myeloid', 'CD4 T cell', 'CD8 T cell', 'B cell', 'Vessel / Endo.']