datasets:
  schulz2024immucan:
    benchmarks:
      cell_annotation: 
        cell_type_atlas:
          label_col: cell_type_atlas
          excluded_classes: [Unknown,]
          cell_types:
            Tumor:
              - Ecad
            Fibroblasts /Stroma:
              - SMA
              - PDGFRb
            Myeloid:
              - CD68
              - CD15
              - CD11c
              - HLADR
            CD4 T cell:
              - CD3
              - CD4
            CD8 T cell:
              - CD3
              - CD8a
            B cell:
              - CD20
          eval_cell_types: ['Tumor', 'Fibroblasts /Stroma', 'Myeloid', 'CD4 T cell', 'CD8 T cell', 'B cell', 'Vessel / Endo.']