datasets:
  fischer2023multiplex:
    name: fischer2023multiplex
    path: /mnt/aimm/scratch/datasets_v2/fischer2023multiplex
    modality: imc
    standardization: quantile_clipping_log1p/uq_0.99_image
    resolution: 1.0
    filter_list: ['gaussian_blur',]
    use_mean_std: True
    disable_quantile_mask: False