datasets:
  lin2023highsubset:
    name: lin2023highsubset
    path: /path/to/datasets/lin2023highsubset
    modality: cycif
    standardization: quantile_clipping_log1p/uq_0.99_image
    resolution: 1.0
    use_mean_std: True
    disable_quantile_mask: False